### ISSUE TITLE
proof generation code

### ISSUE THREAD

**Issue by yakazimir** [NicolasAG/SGinPG#1]
I'm wondering if the code for generating proofs (e.g., the code you mention in the Appendix 6.2) is available somewhere? Also, is there a split that converts the fake entity names (e.g., `ent_13`) back to normal names? 

Apologies if I'm not seeing there in the existing repo. For context, I'm trying to render your proof structures in a slightly different format and add information so having access to the original proof generation methods would be helpful (I'm currently trying to heuristically generate my version from your annotations, which might be error-prone).

**Comment by NicolasAG** [comment]
Thank you for your interest.

I have included the script I used in the `/scripts` folder. The code described in Appendix 6.2 corresponds to the `build_proof_trace()` function of the `csv2txt.py` file.

Note: this code is considered "research code" so it is not clean and may contain debug and/or dead code.
Hope it helps.

**Comment by yakazimir** [comment]
Thank you @NicolasAG. Very helpful indeed!
